### ISSUE TITLE
0.1.4 breaks because renderArgs.elements is always undefined

### ISSUE THREAD

**Issue by thoughtbyte** [4Catalyzer/found-scroll#15]
Hi,

I'm not sure what exactly `renderArgs.elements` is, but the update in v 0.1.4 breaks for our use case.

this code
```javascript
if (renderArgs.location === this.prevRenderArgs.location
  || !(renderArgs.elemtns || renderArgs.error)) {
      // If the location hasn't actually changed, or if we're in a global
      // pending state, don't update the scroll position.
      return;
    }
```

always returns because `elements` is always undefined.

We are using:

react 15.5.4
react-relay 1.4.1
found 0.3.4
found-relay 0.3.0-alpha.9 (tested with most recent alpha also)
farce 0.2.2

I suspect this is because we are using `createFarceRouter` instead of `createBrowserRouter` but I'm not sure

If there is anything you want me to look into, please let me know. i'm happy to debug with a little guidance and to open a pull request.

**Comment by thoughtbyte** [comment]
after some digging it does look like the 0.1.4 update is incompatible with `createFarceRouter`

I'll be happy to open a pr asap if there is a particular way you want to handle this

**Comment by taion** [comment]
Apologies for taking so long to get to this – i must have missed this issue originally. I'm not sure what the problem here might be – we're using these versions just fine, and it hasn't been an issue yet. There should be no difference between using `createBrowserRouter` and using `createFarceRouter`, as the former just wraps the latter anyway.

**Comment by thoughtbyte** [comment]
It appears we were using this incorrectly. We were rendering the `ScrollManager` from within a `Route`s `render` method rather than in the `renser` callback for `createRouter`. We switched that up and it appears to be working.

Thanks!
